name: flutter_screen_time_example
description: "Demonstrates how to use the flutter_screen_time plugin."
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_screen_time:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter  
  integration_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
