name: flutter_screen_time
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shebnik.flutter_screen_time
        pluginClass: FlutterScreenTimePlugin
      ios:
        pluginClass: FlutterScreenTimePlugin
      